name: test_build
description: A new Flutter project.

publish_to:
version: 2.0.0+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^4.3.3
  firebase_core: ^1.0.2
  cloud_firestore: ^1.0.3
  firebase_auth: ^1.0.1
  email_validator: ^1.0.6
  table_calendar: ^2.2.3
  intl: ^0.17.0
  charts_flutter: ^0.10.0
  flutter_slidable: ^0.6.0
  flutter_launcher_icons: ^0.9.0
  flutter_native_splash: ^1.0.0
  introduction_screen: ^2.1.0
  shared_preferences: ^2.0.6
  url_launcher: ^6.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "lib/image/futsal_analysis.png"

flutter_native_splash:
  image: "lib/image/futsal_analysis_512.png"
  color: "242424"


flutter:
 uses-material-design: true
